# Generated by Django 6.0.2 on 2026-02-12 08:41

import backend_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='secret_name',
            field=models.CharField(default=backend_api.models.get_secret_name, max_length=255),
        ),
    ]
