# Generated by Django 6.0.2 on 2026-03-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_storage_secret_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='downloaded_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
